# Generated by Django 5.2.3 on 2025-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='h1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='bez', max_length=120),
            preserve_default=False,
        ),
    ]
