# Generated by Django 5.2.3 on 2025-06-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_h1_game_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('h1', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='text',
            field=models.TextField(default='dfdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
