# Generated by Django 5.2.3 on 2025-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_homepagecontent_game_text_alter_game_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='text',
        ),
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст (HTML без экранирования)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='dsfsdf', max_length=255),
            preserve_default=False,
        ),
    ]
