# Generated by Django 5.2.3 on 2025-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_delete_homepagecontent_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt')),
                ('link_text', models.CharField(max_length=255, verbose_name='Текст ссылки')),
            ],
        ),
    ]
