# Generated by Django 5.2.3 on 2025-06-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type_game',
            field=models.CharField(choices=[('HTML5', 'badge-html5'), ('Flash', 'badge-flash')], default='HTML5', max_length=40),
        ),
    ]
